### ISSUE TITLE
Integration tests should run with every available Serializer

### ISSUE THREAD

**Issue by danmarcab** [MyMedsAndMe/spell#17]
Right now, integration tests are run using `Spell.Serializer.JSON` as default serializer.
We have to provide a way of passing serializer and run the tests multiple times.

`ecto` does something similar for integration testing all the db adapters, providing a test_helper for each adaptor and then requiring the files:
https://github.com/elixir-lang/ecto/blob/master/integration_test/pg/all_test.exs

**Comment by jtmoulia** [comment]
Nice -- I'd been wondering how to do it with ExUnit.

An alternative is [shouldi](https://github.com/batate/shouldi#use-matchers-simplify-tests), which has [matchers](https://github.com/batate/shouldi#use-matchers-simplify-tests) for this type of problem.

**Comment by danmarcab** [comment]
Closed by f2d95fb876531a4d7c526502b55ba5b2a5492b6f
