### ISSUE TITLE
PubSub example is broken

### ISSUE THREAD

**Issue by danmarcab** [MyMedsAndMe/spell#21]
The pubsub example is broken at the moment. 
We should add it to travis to make sure we don't break it again.

**Comment by mtanzi** [comment]
Yes I saw that, I was wondering what will be the best way to check that. Maybe adding the post_script hook to trigger the `run examples/pubsub.exs` or add a new script that run all the examples in the directory and trigger that script

**Comment by danmarcab** [comment]
Fixed by 2c1f06f7e2fc65e98d26a7adc59887f5d7682577

**Comment by danmarcab** [comment]
I am opening a new issue to run all the examples sequentially (not high priority as we have one example at the moment)
