### ISSUE TITLE
Installing from Hex doesn't fetch all dependencies

### ISSUE THREAD

**Issue by cloud8421** [MyMedsAndMe/spell#40]
It seems that only other hex packages are fetched as dependencies of an hex package.

![screenshot 2015-09-14 15 56 31](https://cloud.githubusercontent.com/assets/537608/9852994/47e38136-5af9-11e5-9830-4bcb7689539e.png)

I didn't know about this myself, but I'm seeing errors as it doesn't fetch `websocket_client`.

**Comment by jtmoulia** [comment]
Ouch -- thanks for the report. Will fix ASAP.

**Comment by jtmoulia** [comment]
I opened an issue with websocket_client, https://github.com/jeremyong/websocket_client/issues/44, to try and get the library into hex.

However, given that this is out of our control (can't even publish to hex ourselves because someone is [squatting](https://hex.pm/packages/websocket_client) on the package) and fixing #16 would take care of this issue (Spell's user would have to explicitly include the dependency), I'd like to go ahead and resolve #16. As an interface change, that would bump the vsn to 0.2.0. With the bump, I'd like to also fit in #19 which I'm currently working on.

**Comment by cloud8421** [comment]
That's a good strategy and I definitely agree with #16 

One possible way forward to resolve this is to plug these libraries at the configuration/setup level, like Postgrex does: <https://github.com/ericmj/postgrex#extensions>

This way, if I only use Spell with RawSocket, I can avoid the websockets dependency (or other similar use cases).

What do you think? Thanks for your work on this, BTW!

**Comment by jtmoulia** [comment]
Cool, I like how postgrex handles plugging in libraries -- it's nice to not be constrained to a particular library. But, without adding a translation layer I'm not sure if it would work for the websocket component. For postgrex's JSON extension, it just calls [`encode!/1`](https://github.com/ericmj/postgrex/blob/master/lib/postgrex/extensions/json.ex#L23) and [`decode!/1`](https://github.com/ericmj/postgrex/blob/master/lib/postgrex/extensions/json.ex#L23) on the JSON library module it was configured with. In other words, it requires the JSON library to use a fixed interface. For websocket_client, however, we have to actually implement the websocket_client [callbacks](https://github.com/MyMedsAndMe/spell/blob/master/lib/spell/transport/websocket.ex#L57) -- without a fixed interface across websocket libraries I don't know a simple approach which allows the user to dynamically specify the library.

For JSON or MsgPack, though, it's definitely possible :)

With #16 leaving the dependencies up to the user, it would still be possible to use Spell with only RawSocket, dropping the websocket dependency. The same is true of MsgPack + JSON.

**Comment by cloud8421** [comment]
I see what you mean, makes a lot of sense!

**Comment by jtmoulia** [comment]
Resolved by #42, see #43 for plan to update websocket dep.
